{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "823c9aea-24a5-4056-9679-d3b3ec249efc",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Setup plotting\n",
    "import matplotlib.pyplot as plt\n",
    "plt.style.use('seaborn-v0_8-whitegrid')\n",
    "# Set Matplotlib defaults\n",
    "plt.rc('figure', autolayout=True)\n",
    "plt.rc('axes', labelweight='bold', labelsize='large',\n",
    "       titleweight='bold', titlesize=18, titlepad=10)\n",
    "plt.rc('animation', html='html5')\n",
    "\n",
    "# Setup feedback system\n",
    "from learntools.core import binder\n",
    "binder.bind(globals())\n",
    "from learntools.deep_learning_intro.ex4 import *"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "f46cb4d4-fe20-483a-8b1c-2e3dbb2697a7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-18 21:14:56.416452: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered\n",
      "WARNING: All log messages before absl::InitializeLog() is called are written to STDERR\n",
      "E0000 00:00:1747595696.449106     879 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered\n",
      "E0000 00:00:1747595696.461578     879 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered\n",
      "2025-05-18 21:14:56.590092: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.\n",
      "To enable the following instructions: SSE4.1 SSE4.2 AVX AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Input shape: [18]\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "from sklearn.preprocessing import StandardScaler, OneHotEncoder\n",
    "from sklearn.compose import make_column_transformer\n",
    "from sklearn.model_selection import GroupShuffleSplit\n",
    "\n",
    "from tensorflow import keras\n",
    "from tensorflow.keras import layers\n",
    "from tensorflow.keras import callbacks\n",
    "\n",
    "spotify = pd.read_csv('../data/raw/deep_neural_networks/spotify.csv')\n",
    "\n",
    "X = spotify.copy().dropna()\n",
    "y = X.pop('track_popularity')\n",
    "artists = X['track_artist']\n",
    "\n",
    "features_num = ['danceability', 'energy', 'key', 'loudness', 'mode',\n",
    "                'speechiness', 'acousticness', 'instrumentalness',\n",
    "                'liveness', 'valence', 'tempo', 'duration_ms']\n",
    "features_cat = ['playlist_genre']\n",
    "\n",
    "preprocessor = make_column_transformer(\n",
    "    (StandardScaler(), features_num),\n",
    "    (OneHotEncoder(), features_cat),\n",
    ")\n",
    "\n",
    "# We'll do a \"grouped\" split to keep all of an artist's songs in one\n",
    "# split or the other. This is to help prevent signal leakage.\n",
    "def group_split(X, y, group, train_size=0.75):\n",
    "    splitter = GroupShuffleSplit(train_size=train_size)\n",
    "    train, test = next(splitter.split(X, y, groups=group))\n",
    "    return (X.iloc[train], X.iloc[test], y.iloc[train], y.iloc[test])\n",
    "\n",
    "X_train, X_valid, y_train, y_valid = group_split(X, y, artists)\n",
    "\n",
    "X_train = preprocessor.fit_transform(X_train)\n",
    "X_valid = preprocessor.transform(X_valid)\n",
    "y_train = y_train / 100 # popularity is on a scale 0-100, so this rescales to 0-1.\n",
    "y_valid = y_valid / 100\n",
    "\n",
    "input_shape = [X_train.shape[1]]\n",
    "print(\"Input shape: {}\".format(input_shape))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3fbcd09d-6d93-4978-a770-574e44598d3f",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n",
      "I0000 00:00:1747595861.185309     879 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1767 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3050 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6\n",
      "W0000 00:00:1747595861.832407   27171 gpu_backend_lib.cc:579] Can't find libdevice directory ${CUDA_DIR}/nvvm/libdevice. This may result in compilation or runtime failures, if the program we try to run uses routines from libdevice.\n",
      "Searched for CUDA in the following directories:\n",
      "  ./cuda_sdk_lib\n",
      "  ipykernel_launcher.runfiles/cuda_nvcc\n",
      "  ipykern/cuda_nvcc\n",
      "  \n",
      "  /usr/local/cuda\n",
      "  /home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tensorflow/python/platform/../../../nvidia/cuda_nvcc\n",
      "  /home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tensorflow/python/platform/../../../../nvidia/cuda_nvcc\n",
      "  /home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tensorflow/python/platform/../../cuda\n",
      "  .\n",
      "You can choose the search directory by setting xla_gpu_cuda_data_dir in HloModule's DebugOptions.  For most apps, setting the environment variable XLA_FLAGS=--xla_gpu_cuda_data_dir=/path/to/cuda will work.\n",
      "I0000 00:00:1747595863.604253   27163 service.cc:148] XLA service 0x7f67a80065f0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:\n",
      "I0000 00:00:1747595863.604311   27163 service.cc:156]   StreamExecutor device (0): NVIDIA GeForce RTX 3050 Laptop GPU, Compute Capability 8.6\n",
      "2025-05-18 21:17:43.666331: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.\n",
      "I0000 00:00:1747595863.780638   27163 cuda_dnn.cc:529] Loaded cuDNN version 90800\n",
      "W0000 00:00:1747595863.976195   27163 gpu_backend_lib.cc:617] libdevice is required by this HLO module but was not found at ./libdevice.10.bc\n",
      "2025-05-18 21:17:43.979354: W tensorflow/core/framework/op_kernel.cc:1841] OP_REQUIRES failed at xla_ops.cc:577 : INTERNAL: libdevice not found at ./libdevice.10.bc\n",
      "2025-05-18 21:17:43.979496: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INTERNAL: libdevice not found at ./libdevice.10.bc\n",
      "\t [[{{node StatefulPartitionedCall}}]]\n"
     ]
    },
    {
     "ename": "InternalError",
     "evalue": "Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 645, in run_forever\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 1999, in _run_once\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3153, in _run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3365, in run_cell_async\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3610, in run_ast_nodes\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3670, in run_code\n\n  File \"/tmp/ipykernel_879/1440710233.py\", line 8, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nlibdevice not found at ./libdevice.10.bc\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_606]",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mInternalError\u001b[39m                             Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[3]\u001b[39m\u001b[32m, line 8\u001b[39m\n\u001b[32m      1\u001b[39m model = keras.Sequential([\n\u001b[32m      2\u001b[39m     layers.Dense(\u001b[32m1\u001b[39m, input_shape=input_shape),\n\u001b[32m      3\u001b[39m ])\n\u001b[32m      4\u001b[39m model.compile(\n\u001b[32m      5\u001b[39m     optimizer=\u001b[33m'\u001b[39m\u001b[33madam\u001b[39m\u001b[33m'\u001b[39m,\n\u001b[32m      6\u001b[39m     loss=\u001b[33m'\u001b[39m\u001b[33mmae\u001b[39m\u001b[33m'\u001b[39m,\n\u001b[32m      7\u001b[39m )\n\u001b[32m----> \u001b[39m\u001b[32m8\u001b[39m history = \u001b[43mmodel\u001b[49m\u001b[43m.\u001b[49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m      9\u001b[39m \u001b[43m    \u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     10\u001b[39m \u001b[43m    \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_valid\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_valid\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     11\u001b[39m \u001b[43m    \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m512\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m     12\u001b[39m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m50\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m     13\u001b[39m \u001b[43m    \u001b[49m\u001b[43mverbose\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m0\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;66;43;03m# suppress output since we'll plot the curves\u001b[39;49;00m\n\u001b[32m     14\u001b[39m \u001b[43m)\u001b[49m\n\u001b[32m     15\u001b[39m history_df = pd.DataFrame(history.history)\n\u001b[32m     16\u001b[39m history_df.loc[\u001b[32m0\u001b[39m:, [\u001b[33m'\u001b[39m\u001b[33mloss\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mval_loss\u001b[39m\u001b[33m'\u001b[39m]].plot()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[39m, in \u001b[36mfilter_traceback.<locals>.error_handler\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    119\u001b[39m     filtered_tb = _process_traceback_frames(e.__traceback__)\n\u001b[32m    120\u001b[39m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[32m    121\u001b[39m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m122\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m e.with_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    123\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    124\u001b[39m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tensorflow/python/eager/execute.py:53\u001b[39m, in \u001b[36mquick_execute\u001b[39m\u001b[34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[39m\n\u001b[32m     51\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m     52\u001b[39m   ctx.ensure_initialized()\n\u001b[32m---> \u001b[39m\u001b[32m53\u001b[39m   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[32m     54\u001b[39m                                       inputs, attrs, num_outputs)\n\u001b[32m     55\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m core._NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m     56\u001b[39m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[31mInternalError\u001b[39m: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 645, in run_forever\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 1999, in _run_once\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3153, in _run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3365, in run_cell_async\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3610, in run_ast_nodes\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3670, in run_code\n\n  File \"/tmp/ipykernel_879/1440710233.py\", line 8, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nlibdevice not found at ./libdevice.10.bc\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_606]"
     ]
    }
   ],
   "source": [
    "model = keras.Sequential([\n",
    "    layers.Dense(1, input_shape=input_shape),\n",
    "])\n",
    "model.compile(\n",
    "    optimizer='adam',\n",
    "    loss='mae',\n",
    ")\n",
    "history = model.fit(\n",
    "    X_train, y_train,\n",
    "    validation_data=(X_valid, y_valid),\n",
    "    batch_size=512,\n",
    "    epochs=50,\n",
    "    verbose=0, # suppress output since we'll plot the curves\n",
    ")\n",
    "history_df = pd.DataFrame(history.history)\n",
    "history_df.loc[0:, ['loss', 'val_loss']].plot()\n",
    "print(\"Minimum Validation Loss: {:0.4f}\".format(history_df['val_loss'].min()));"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "a22c2416-dcb8-4914-8ff9-b8152f61995b",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'history_df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[4]\u001b[39m\u001b[32m, line 2\u001b[39m\n\u001b[32m      1\u001b[39m \u001b[38;5;66;03m# Start the plot at epoch 10\u001b[39;00m\n\u001b[32m----> \u001b[39m\u001b[32m2\u001b[39m \u001b[43mhistory_df\u001b[49m.loc[\u001b[32m10\u001b[39m:, [\u001b[33m'\u001b[39m\u001b[33mloss\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mval_loss\u001b[39m\u001b[33m'\u001b[39m]].plot()\n\u001b[32m      3\u001b[39m \u001b[38;5;28mprint\u001b[39m(\u001b[33m\"\u001b[39m\u001b[33mMinimum Validation Loss: \u001b[39m\u001b[38;5;132;01m{:0.4f}\u001b[39;00m\u001b[33m\"\u001b[39m.format(history_df[\u001b[33m'\u001b[39m\u001b[33mval_loss\u001b[39m\u001b[33m'\u001b[39m].min()));\n",
      "\u001b[31mNameError\u001b[39m: name 'history_df' is not defined"
     ]
    }
   ],
   "source": [
    "# Start the plot at epoch 10\n",
    "history_df.loc[10:, ['loss', 'val_loss']].plot()\n",
    "print(\"Minimum Validation Loss: {:0.4f}\".format(history_df['val_loss'].min()));"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e04c7ac9-4283-48d9-88f2-2b975c357a6c",
   "metadata": {},
   "source": [
    "## 1) Evaluate baseline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "14b43f7f-416f-44de-a5bc-33da14fb2e7c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/javascript": [
       "parent.postMessage({\"jupyterEvent\": \"custom.exercise_interaction\", \"data\": {\"outcomeType\": 1, \"valueTowardsCompletion\": 0.25, \"interactionType\": 1, \"questionType\": 4, \"questionId\": \"1_Q1\", \"learnToolsVersion\": \"0.3.5\", \"failureMessage\": \"\", \"exceptionClass\": \"\", \"trace\": \"\"}}, \"*\")"
      ],
      "text/plain": [
       "<IPython.core.display.Javascript object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/markdown": [
       "<span style=\"color:#33cc33\">Correct:</span> \n",
       "\n",
       "The gap between these curves is quite small and the validation loss never increases, so it's more likely that the network is underfitting than overfitting. It would be worth experimenting with more capacity to see if that's the case."
      ],
      "text/plain": [
       "Correct: \n",
       "\n",
       "The gap between these curves is quite small and the validation loss never increases, so it's more likely that the network is underfitting than overfitting. It would be worth experimenting with more capacity to see if that's the case."
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# View the solution (Run this cell to receive credit!)\n",
    "q_1.check()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "fa2914f8-cc0a-44bf-b248-20dffe8f61b0",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.\n",
      "  super().__init__(activity_regularizer=activity_regularizer, **kwargs)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/50\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "E0000 00:00:1747597371.533574   27163 buffer_comparator.cc:157] Difference at 16: 0, expected 264.876\n",
      "E0000 00:00:1747597371.533714   27163 buffer_comparator.cc:157] Difference at 17: 0, expected 253.655\n",
      "E0000 00:00:1747597371.533725   27163 buffer_comparator.cc:157] Difference at 18: 0, expected 244.343\n",
      "E0000 00:00:1747597371.533730   27163 buffer_comparator.cc:157] Difference at 19: 0, expected 250.485\n",
      "E0000 00:00:1747597371.533733   27163 buffer_comparator.cc:157] Difference at 20: 0, expected 246.392\n",
      "E0000 00:00:1747597371.533737   27163 buffer_comparator.cc:157] Difference at 21: 0, expected 249.136\n",
      "E0000 00:00:1747597371.533740   27163 buffer_comparator.cc:157] Difference at 22: 0, expected 256.307\n",
      "E0000 00:00:1747597371.533744   27163 buffer_comparator.cc:157] Difference at 23: 0, expected 246.965\n",
      "E0000 00:00:1747597371.533747   27163 buffer_comparator.cc:157] Difference at 24: 0, expected 256.769\n",
      "E0000 00:00:1747597371.533750   27163 buffer_comparator.cc:157] Difference at 25: 0, expected 251.869\n",
      "2025-05-18 21:42:51.533763: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.538314   27163 buffer_comparator.cc:157] Difference at 16: 0, expected 264.876\n",
      "E0000 00:00:1747597371.538374   27163 buffer_comparator.cc:157] Difference at 17: 0, expected 253.655\n",
      "E0000 00:00:1747597371.538384   27163 buffer_comparator.cc:157] Difference at 18: 0, expected 244.343\n",
      "E0000 00:00:1747597371.538388   27163 buffer_comparator.cc:157] Difference at 19: 0, expected 250.485\n",
      "E0000 00:00:1747597371.538391   27163 buffer_comparator.cc:157] Difference at 20: 0, expected 246.392\n",
      "E0000 00:00:1747597371.538395   27163 buffer_comparator.cc:157] Difference at 21: 0, expected 249.136\n",
      "E0000 00:00:1747597371.538398   27163 buffer_comparator.cc:157] Difference at 22: 0, expected 256.307\n",
      "E0000 00:00:1747597371.538402   27163 buffer_comparator.cc:157] Difference at 23: 0, expected 246.965\n",
      "E0000 00:00:1747597371.538405   27163 buffer_comparator.cc:157] Difference at 24: 0, expected 256.769\n",
      "E0000 00:00:1747597371.538409   27163 buffer_comparator.cc:157] Difference at 25: 0, expected 251.869\n",
      "2025-05-18 21:42:51.538419: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.542602   27163 buffer_comparator.cc:157] Difference at 16: 0, expected 264.876\n",
      "E0000 00:00:1747597371.542658   27163 buffer_comparator.cc:157] Difference at 17: 0, expected 253.655\n",
      "E0000 00:00:1747597371.542668   27163 buffer_comparator.cc:157] Difference at 18: 0, expected 244.343\n",
      "E0000 00:00:1747597371.542672   27163 buffer_comparator.cc:157] Difference at 19: 0, expected 250.485\n",
      "E0000 00:00:1747597371.542676   27163 buffer_comparator.cc:157] Difference at 20: 0, expected 246.392\n",
      "E0000 00:00:1747597371.542680   27163 buffer_comparator.cc:157] Difference at 21: 0, expected 249.136\n",
      "E0000 00:00:1747597371.542683   27163 buffer_comparator.cc:157] Difference at 22: 0, expected 256.307\n",
      "E0000 00:00:1747597371.542686   27163 buffer_comparator.cc:157] Difference at 23: 0, expected 246.965\n",
      "E0000 00:00:1747597371.542690   27163 buffer_comparator.cc:157] Difference at 24: 0, expected 256.769\n",
      "E0000 00:00:1747597371.542693   27163 buffer_comparator.cc:157] Difference at 25: 0, expected 251.869\n",
      "2025-05-18 21:42:51.542701: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.548232   27163 buffer_comparator.cc:157] Difference at 1: 290.553, expected 256.133\n",
      "E0000 00:00:1747597371.548324   27163 buffer_comparator.cc:157] Difference at 2: 296.042, expected 258.13\n",
      "E0000 00:00:1747597371.548339   27163 buffer_comparator.cc:157] Difference at 3: 298.279, expected 259.283\n",
      "E0000 00:00:1747597371.549780   27163 buffer_comparator.cc:157] Difference at 6: 304.153, expected 262.422\n",
      "E0000 00:00:1747597371.549846   27163 buffer_comparator.cc:157] Difference at 12: 293.764, expected 256.602\n",
      "E0000 00:00:1747597371.549856   27163 buffer_comparator.cc:157] Difference at 16: 312.238, expected 264.876\n",
      "E0000 00:00:1747597371.549862   27163 buffer_comparator.cc:157] Difference at 18: 279.657, expected 244.343\n",
      "E0000 00:00:1747597371.549868   27163 buffer_comparator.cc:157] Difference at 23: 282.407, expected 246.965\n",
      "E0000 00:00:1747597371.549874   27163 buffer_comparator.cc:157] Difference at 26: 302.46, expected 261.981\n",
      "E0000 00:00:1747597371.549880   27163 buffer_comparator.cc:157] Difference at 27: 296.528, expected 257.078\n",
      "2025-05-18 21:42:51.549894: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.555180   27163 buffer_comparator.cc:157] Difference at 1024: 0, expected 237.739\n",
      "E0000 00:00:1747597371.555246   27163 buffer_comparator.cc:157] Difference at 1025: 0, expected 245.649\n",
      "E0000 00:00:1747597371.555255   27163 buffer_comparator.cc:157] Difference at 1026: 0, expected 247.122\n",
      "E0000 00:00:1747597371.555259   27163 buffer_comparator.cc:157] Difference at 1027: 0, expected 247.354\n",
      "E0000 00:00:1747597371.555263   27163 buffer_comparator.cc:157] Difference at 1028: 0, expected 242.359\n",
      "E0000 00:00:1747597371.555267   27163 buffer_comparator.cc:157] Difference at 1029: 0, expected 243.689\n",
      "E0000 00:00:1747597371.555270   27163 buffer_comparator.cc:157] Difference at 1030: 0, expected 249.288\n",
      "E0000 00:00:1747597371.555274   27163 buffer_comparator.cc:157] Difference at 1031: 0, expected 230.812\n",
      "E0000 00:00:1747597371.555277   27163 buffer_comparator.cc:157] Difference at 1032: 0, expected 234.886\n",
      "E0000 00:00:1747597371.555281   27163 buffer_comparator.cc:157] Difference at 1033: 0, expected 236.903\n",
      "2025-05-18 21:42:51.555292: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.561675   27163 buffer_comparator.cc:157] Difference at 1040: 0, expected 250.885\n",
      "E0000 00:00:1747597371.561772   27163 buffer_comparator.cc:157] Difference at 1041: 0, expected 242.891\n",
      "E0000 00:00:1747597371.561786   27163 buffer_comparator.cc:157] Difference at 1042: 0, expected 234.66\n",
      "E0000 00:00:1747597371.561792   27163 buffer_comparator.cc:157] Difference at 1043: 0, expected 245.705\n",
      "E0000 00:00:1747597371.561798   27163 buffer_comparator.cc:157] Difference at 1044: 0, expected 240.405\n",
      "E0000 00:00:1747597371.561803   27163 buffer_comparator.cc:157] Difference at 1045: 0, expected 240.338\n",
      "E0000 00:00:1747597371.561809   27163 buffer_comparator.cc:157] Difference at 1046: 0, expected 252.252\n",
      "E0000 00:00:1747597371.561819   27163 buffer_comparator.cc:157] Difference at 1047: 0, expected 239.308\n",
      "E0000 00:00:1747597371.561826   27163 buffer_comparator.cc:157] Difference at 1048: 0, expected 244.229\n",
      "E0000 00:00:1747597371.561832   27163 buffer_comparator.cc:157] Difference at 1049: 0, expected 237.234\n",
      "2025-05-18 21:42:51.561847: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.569370   27163 buffer_comparator.cc:157] Difference at 1056: 0, expected 237.185\n",
      "E0000 00:00:1747597371.569469   27163 buffer_comparator.cc:157] Difference at 1057: 0, expected 241.68\n",
      "E0000 00:00:1747597371.569483   27163 buffer_comparator.cc:157] Difference at 1058: 0, expected 245.792\n",
      "E0000 00:00:1747597371.569490   27163 buffer_comparator.cc:157] Difference at 1059: 0, expected 242.505\n",
      "E0000 00:00:1747597371.569497   27163 buffer_comparator.cc:157] Difference at 1060: 0, expected 248.023\n",
      "E0000 00:00:1747597371.569503   27163 buffer_comparator.cc:157] Difference at 1061: 0, expected 256.815\n",
      "E0000 00:00:1747597371.569510   27163 buffer_comparator.cc:157] Difference at 1062: 0, expected 243.999\n",
      "E0000 00:00:1747597371.569516   27163 buffer_comparator.cc:157] Difference at 1063: 0, expected 233.91\n",
      "E0000 00:00:1747597371.569522   27163 buffer_comparator.cc:157] Difference at 1064: 0, expected 246.308\n",
      "E0000 00:00:1747597371.569528   27163 buffer_comparator.cc:157] Difference at 1065: 0, expected 242.466\n",
      "2025-05-18 21:42:51.569544: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.574116   27163 buffer_comparator.cc:157] Difference at 2048: 0, expected 352.221\n",
      "E0000 00:00:1747597371.574196   27163 buffer_comparator.cc:157] Difference at 2049: 0, expected 357.403\n",
      "E0000 00:00:1747597371.574209   27163 buffer_comparator.cc:157] Difference at 2050: 0, expected 354.138\n",
      "E0000 00:00:1747597371.574217   27163 buffer_comparator.cc:157] Difference at 2051: 0, expected 358.733\n",
      "E0000 00:00:1747597371.574223   27163 buffer_comparator.cc:157] Difference at 2052: 0, expected 352.416\n",
      "E0000 00:00:1747597371.574229   27163 buffer_comparator.cc:157] Difference at 2053: 0, expected 352.369\n",
      "E0000 00:00:1747597371.574235   27163 buffer_comparator.cc:157] Difference at 2054: 0, expected 363.764\n",
      "E0000 00:00:1747597371.574241   27163 buffer_comparator.cc:157] Difference at 2055: 0, expected 338.576\n",
      "E0000 00:00:1747597371.574248   27163 buffer_comparator.cc:157] Difference at 2056: 0, expected 342.664\n",
      "E0000 00:00:1747597371.574254   27163 buffer_comparator.cc:157] Difference at 2057: 0, expected 345.361\n",
      "2025-05-18 21:42:51.574267: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.578338   27163 buffer_comparator.cc:157] Difference at 3: 289.623, expected 259.283\n",
      "E0000 00:00:1747597371.578407   27163 buffer_comparator.cc:157] Difference at 27: 286.065, expected 257.078\n",
      "E0000 00:00:1747597371.578421   27163 buffer_comparator.cc:157] Difference at 40: 287.554, expected 255.205\n",
      "E0000 00:00:1747597371.578429   27163 buffer_comparator.cc:157] Difference at 42: 280.997, expected 248.623\n",
      "E0000 00:00:1747597371.578436   27163 buffer_comparator.cc:157] Difference at 49: 304.787, expected 258.681\n",
      "E0000 00:00:1747597371.578443   27163 buffer_comparator.cc:157] Difference at 61: 285.495, expected 255.235\n",
      "E0000 00:00:1747597371.578448   27163 buffer_comparator.cc:157] Difference at 67: 267.628, expected 232.294\n",
      "E0000 00:00:1747597371.578452   27163 buffer_comparator.cc:157] Difference at 106: 251.898, expected 222.773\n",
      "E0000 00:00:1747597371.578456   27163 buffer_comparator.cc:157] Difference at 113: 254.068, expected 226.108\n",
      "E0000 00:00:1747597371.578460   27163 buffer_comparator.cc:157] Difference at 131: 157.504, expected 130.874\n",
      "2025-05-18 21:42:51.578469: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.582586   27163 buffer_comparator.cc:157] Difference at 1: 326.975, expected 256.133\n",
      "E0000 00:00:1747597371.582640   27163 buffer_comparator.cc:157] Difference at 2: 297.578, expected 258.13\n",
      "E0000 00:00:1747597371.582649   27163 buffer_comparator.cc:157] Difference at 3: 309.091, expected 259.283\n",
      "E0000 00:00:1747597371.582652   27163 buffer_comparator.cc:157] Difference at 5: 297.859, expected 254.784\n",
      "E0000 00:00:1747597371.582657   27163 buffer_comparator.cc:157] Difference at 6: 322.817, expected 262.422\n",
      "E0000 00:00:1747597371.582661   27163 buffer_comparator.cc:157] Difference at 8: 279.5, expected 246.547\n",
      "E0000 00:00:1747597371.582664   27163 buffer_comparator.cc:157] Difference at 11: 213.098, expected 246.933\n",
      "E0000 00:00:1747597371.582668   27163 buffer_comparator.cc:157] Difference at 12: 292.475, expected 256.602\n",
      "E0000 00:00:1747597371.582672   27163 buffer_comparator.cc:157] Difference at 14: 296.15, expected 259.382\n",
      "E0000 00:00:1747597371.582675   27163 buffer_comparator.cc:157] Difference at 16: 342.083, expected 264.876\n",
      "2025-05-18 21:42:51.582684: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.586424   27163 buffer_comparator.cc:157] Difference at 32: 419.349, expected 252.215\n",
      "E0000 00:00:1747597371.586477   27163 buffer_comparator.cc:157] Difference at 33: 407.885, expected 250.388\n",
      "E0000 00:00:1747597371.586486   27163 buffer_comparator.cc:157] Difference at 34: 409.923, expected 260.173\n",
      "E0000 00:00:1747597371.586490   27163 buffer_comparator.cc:157] Difference at 35: 416.571, expected 253.656\n",
      "E0000 00:00:1747597371.586495   27163 buffer_comparator.cc:157] Difference at 36: 386.894, expected 252.701\n",
      "E0000 00:00:1747597371.586499   27163 buffer_comparator.cc:157] Difference at 37: 436.727, expected 269.757\n",
      "E0000 00:00:1747597371.586503   27163 buffer_comparator.cc:157] Difference at 38: 423.666, expected 253.712\n",
      "E0000 00:00:1747597371.586506   27163 buffer_comparator.cc:157] Difference at 39: 412.322, expected 245.159\n",
      "E0000 00:00:1747597371.586510   27163 buffer_comparator.cc:157] Difference at 40: 430.911, expected 255.205\n",
      "E0000 00:00:1747597371.586513   27163 buffer_comparator.cc:157] Difference at 41: 410.439, expected 252.267\n",
      "2025-05-18 21:42:51.586522: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.590868   27163 buffer_comparator.cc:157] Difference at 32: 419.349, expected 252.215\n",
      "E0000 00:00:1747597371.590928   27163 buffer_comparator.cc:157] Difference at 33: 407.885, expected 250.388\n",
      "E0000 00:00:1747597371.590937   27163 buffer_comparator.cc:157] Difference at 34: 409.923, expected 260.173\n",
      "E0000 00:00:1747597371.590941   27163 buffer_comparator.cc:157] Difference at 35: 416.571, expected 253.656\n",
      "E0000 00:00:1747597371.590945   27163 buffer_comparator.cc:157] Difference at 36: 386.894, expected 252.701\n",
      "E0000 00:00:1747597371.590948   27163 buffer_comparator.cc:157] Difference at 37: 436.727, expected 269.757\n",
      "E0000 00:00:1747597371.590952   27163 buffer_comparator.cc:157] Difference at 38: 423.666, expected 253.712\n",
      "E0000 00:00:1747597371.590955   27163 buffer_comparator.cc:157] Difference at 39: 412.322, expected 245.159\n",
      "E0000 00:00:1747597371.590959   27163 buffer_comparator.cc:157] Difference at 40: 430.911, expected 255.205\n",
      "E0000 00:00:1747597371.590963   27163 buffer_comparator.cc:157] Difference at 41: 410.439, expected 252.267\n",
      "2025-05-18 21:42:51.590972: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.595216   27163 buffer_comparator.cc:157] Difference at 4096: 4.25582, expected 295.966\n",
      "E0000 00:00:1747597371.595277   27163 buffer_comparator.cc:157] Difference at 4097: 3.83629, expected 297.85\n",
      "E0000 00:00:1747597371.595287   27163 buffer_comparator.cc:157] Difference at 4098: 6.51513, expected 300.911\n",
      "E0000 00:00:1747597371.595291   27163 buffer_comparator.cc:157] Difference at 4099: 4.85554, expected 301.47\n",
      "E0000 00:00:1747597371.595295   27163 buffer_comparator.cc:157] Difference at 4100: 5.99832, expected 296.586\n",
      "E0000 00:00:1747597371.595298   27163 buffer_comparator.cc:157] Difference at 4101: 6.73417, expected 301.246\n",
      "E0000 00:00:1747597371.595302   27163 buffer_comparator.cc:157] Difference at 4102: 7.01154, expected 305.284\n",
      "E0000 00:00:1747597371.595306   27163 buffer_comparator.cc:157] Difference at 4103: 7.4551, expected 282.733\n",
      "E0000 00:00:1747597371.595309   27163 buffer_comparator.cc:157] Difference at 4104: 4.64991, expected 284.502\n",
      "E0000 00:00:1747597371.595312   27163 buffer_comparator.cc:157] Difference at 4105: 2.74421, expected 289.553\n",
      "2025-05-18 21:42:51.595322: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.599229   27163 buffer_comparator.cc:157] Difference at 4096: 4.25582, expected 295.966\n",
      "E0000 00:00:1747597371.599291   27163 buffer_comparator.cc:157] Difference at 4097: 3.83629, expected 297.85\n",
      "E0000 00:00:1747597371.599300   27163 buffer_comparator.cc:157] Difference at 4098: 6.51513, expected 300.911\n",
      "E0000 00:00:1747597371.599304   27163 buffer_comparator.cc:157] Difference at 4099: 4.85554, expected 301.47\n",
      "E0000 00:00:1747597371.599309   27163 buffer_comparator.cc:157] Difference at 4100: 5.99832, expected 296.586\n",
      "E0000 00:00:1747597371.599312   27163 buffer_comparator.cc:157] Difference at 4101: 6.73417, expected 301.246\n",
      "E0000 00:00:1747597371.599316   27163 buffer_comparator.cc:157] Difference at 4102: 7.01154, expected 305.284\n",
      "E0000 00:00:1747597371.599319   27163 buffer_comparator.cc:157] Difference at 4103: 7.4551, expected 282.733\n",
      "E0000 00:00:1747597371.599323   27163 buffer_comparator.cc:157] Difference at 4104: 4.64991, expected 284.502\n",
      "E0000 00:00:1747597371.599326   27163 buffer_comparator.cc:157] Difference at 4105: 2.74421, expected 289.553\n",
      "2025-05-18 21:42:51.599335: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.610438   27163 buffer_comparator.cc:157] Difference at 1216: 110.999, expected 124.526\n",
      "E0000 00:00:1747597371.610498   27163 buffer_comparator.cc:157] Difference at 1217: 112.213, expected 129.215\n",
      "E0000 00:00:1747597371.610523   27163 buffer_comparator.cc:157] Difference at 5451: 125.092, expected 139.733\n",
      "2025-05-18 21:42:51.610543: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.615517   27163 buffer_comparator.cc:157] Difference at 3: 289.623, expected 259.283\n",
      "E0000 00:00:1747597371.615587   27163 buffer_comparator.cc:157] Difference at 27: 286.065, expected 257.078\n",
      "E0000 00:00:1747597371.615597   27163 buffer_comparator.cc:157] Difference at 40: 287.554, expected 255.205\n",
      "E0000 00:00:1747597371.615601   27163 buffer_comparator.cc:157] Difference at 42: 280.997, expected 248.623\n",
      "E0000 00:00:1747597371.615605   27163 buffer_comparator.cc:157] Difference at 49: 304.787, expected 258.681\n",
      "E0000 00:00:1747597371.615610   27163 buffer_comparator.cc:157] Difference at 61: 285.495, expected 255.235\n",
      "E0000 00:00:1747597371.615614   27163 buffer_comparator.cc:157] Difference at 67: 267.628, expected 232.294\n",
      "E0000 00:00:1747597371.615618   27163 buffer_comparator.cc:157] Difference at 106: 251.898, expected 222.773\n",
      "E0000 00:00:1747597371.615622   27163 buffer_comparator.cc:157] Difference at 113: 254.068, expected 226.108\n",
      "E0000 00:00:1747597371.615626   27163 buffer_comparator.cc:157] Difference at 131: 157.504, expected 130.874\n",
      "2025-05-18 21:42:51.615636: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.621114   27163 buffer_comparator.cc:157] Difference at 16: 292.867, expected 74.4591\n",
      "E0000 00:00:1747597371.621183   27163 buffer_comparator.cc:157] Difference at 17: 258.6, expected 66.3701\n",
      "E0000 00:00:1747597371.621193   27163 buffer_comparator.cc:157] Difference at 18: 245.29, expected 68.8619\n",
      "E0000 00:00:1747597371.621198   27163 buffer_comparator.cc:157] Difference at 19: 262.474, expected 71.1305\n",
      "E0000 00:00:1747597371.621202   27163 buffer_comparator.cc:157] Difference at 20: 259.544, expected 67.7619\n",
      "E0000 00:00:1747597371.621206   27163 buffer_comparator.cc:157] Difference at 21: 243.815, expected 67.3062\n",
      "E0000 00:00:1747597371.621209   27163 buffer_comparator.cc:157] Difference at 22: 264.012, expected 68.2975\n",
      "E0000 00:00:1747597371.621213   27163 buffer_comparator.cc:157] Difference at 23: 256.767, expected 59.5664\n",
      "E0000 00:00:1747597371.621217   27163 buffer_comparator.cc:157] Difference at 24: 266.422, expected 69.2017\n",
      "E0000 00:00:1747597371.621220   27163 buffer_comparator.cc:157] Difference at 25: 269.175, expected 68.5863\n",
      "2025-05-18 21:42:51.621230: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.624432   27163 buffer_comparator.cc:157] Difference at 16: 292.867, expected 74.4591\n",
      "E0000 00:00:1747597371.624483   27163 buffer_comparator.cc:157] Difference at 17: 258.6, expected 66.3701\n",
      "E0000 00:00:1747597371.624492   27163 buffer_comparator.cc:157] Difference at 18: 245.29, expected 68.8619\n",
      "E0000 00:00:1747597371.624496   27163 buffer_comparator.cc:157] Difference at 19: 262.474, expected 71.1305\n",
      "E0000 00:00:1747597371.624501   27163 buffer_comparator.cc:157] Difference at 20: 259.544, expected 67.7619\n",
      "E0000 00:00:1747597371.624504   27163 buffer_comparator.cc:157] Difference at 21: 243.815, expected 67.3062\n",
      "E0000 00:00:1747597371.624508   27163 buffer_comparator.cc:157] Difference at 22: 264.012, expected 68.2975\n",
      "E0000 00:00:1747597371.624511   27163 buffer_comparator.cc:157] Difference at 23: 256.767, expected 59.5664\n",
      "E0000 00:00:1747597371.624515   27163 buffer_comparator.cc:157] Difference at 24: 266.422, expected 69.2017\n",
      "E0000 00:00:1747597371.624519   27163 buffer_comparator.cc:157] Difference at 25: 269.175, expected 68.5863\n",
      "2025-05-18 21:42:51.624527: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.628777   27163 buffer_comparator.cc:157] Difference at 4: 74.0131, expected 64.6046\n",
      "E0000 00:00:1747597371.628848   27163 buffer_comparator.cc:157] Difference at 25: 76.4552, expected 68.5863\n",
      "E0000 00:00:1747597371.628862   27163 buffer_comparator.cc:157] Difference at 43: 57.5264, expected 64.6972\n",
      "E0000 00:00:1747597371.628869   27163 buffer_comparator.cc:157] Difference at 60: 71.8947, expected 64.4762\n",
      "E0000 00:00:1747597371.628875   27163 buffer_comparator.cc:157] Difference at 68: 72.3583, expected 62.385\n",
      "E0000 00:00:1747597371.628882   27163 buffer_comparator.cc:157] Difference at 132: 66.3846, expected 58.9071\n",
      "E0000 00:00:1747597371.628889   27163 buffer_comparator.cc:157] Difference at 153: 69.2428, expected 61.4907\n",
      "E0000 00:00:1747597371.628896   27163 buffer_comparator.cc:157] Difference at 188: 66.0781, expected 57.3868\n",
      "E0000 00:00:1747597371.628903   27163 buffer_comparator.cc:157] Difference at 196: 69.6591, expected 60.5085\n",
      "E0000 00:00:1747597371.628910   27163 buffer_comparator.cc:157] Difference at 217: 72.8988, expected 64.6393\n",
      "2025-05-18 21:42:51.628921: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.632859   27163 buffer_comparator.cc:157] Difference at 1024: 75.8389, expected 65.4676\n",
      "E0000 00:00:1747597371.632913   27163 buffer_comparator.cc:157] Difference at 1025: 83.3407, expected 62.7145\n",
      "E0000 00:00:1747597371.632922   27163 buffer_comparator.cc:157] Difference at 1026: 83.7652, expected 69.3355\n",
      "E0000 00:00:1747597371.632926   27163 buffer_comparator.cc:157] Difference at 1027: 88.5472, expected 71.8848\n",
      "E0000 00:00:1747597371.632930   27163 buffer_comparator.cc:157] Difference at 1028: 76.5048, expected 60.1548\n",
      "E0000 00:00:1747597371.632933   27163 buffer_comparator.cc:157] Difference at 1029: 80.0078, expected 66.3009\n",
      "E0000 00:00:1747597371.632937   27163 buffer_comparator.cc:157] Difference at 1030: 83.1912, expected 69.2194\n",
      "E0000 00:00:1747597371.632941   27163 buffer_comparator.cc:157] Difference at 1031: 76.5325, expected 60.5966\n",
      "E0000 00:00:1747597371.632944   27163 buffer_comparator.cc:157] Difference at 1032: 82.2318, expected 64.6332\n",
      "E0000 00:00:1747597371.632948   27163 buffer_comparator.cc:157] Difference at 1033: 71.7987, expected 62.779\n",
      "2025-05-18 21:42:51.632956: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.637382   27163 buffer_comparator.cc:157] Difference at 1040: 89.3169, expected 71.7533\n",
      "E0000 00:00:1747597371.637449   27163 buffer_comparator.cc:157] Difference at 1041: 77.1401, expected 64.2298\n",
      "E0000 00:00:1747597371.637459   27163 buffer_comparator.cc:157] Difference at 1043: 82.4868, expected 66.5319\n",
      "E0000 00:00:1747597371.637463   27163 buffer_comparator.cc:157] Difference at 1044: 76.7517, expected 67.6749\n",
      "E0000 00:00:1747597371.637467   27163 buffer_comparator.cc:157] Difference at 1046: 80.2139, expected 68.5063\n",
      "E0000 00:00:1747597371.637471   27163 buffer_comparator.cc:157] Difference at 1047: 76.4964, expected 61.9326\n",
      "E0000 00:00:1747597371.637475   27163 buffer_comparator.cc:157] Difference at 1048: 80.8519, expected 65.6029\n",
      "E0000 00:00:1747597371.637478   27163 buffer_comparator.cc:157] Difference at 1049: 77.8709, expected 64.3103\n",
      "E0000 00:00:1747597371.637482   27163 buffer_comparator.cc:157] Difference at 1050: 85.1314, expected 65.974\n",
      "E0000 00:00:1747597371.637485   27163 buffer_comparator.cc:157] Difference at 1051: 83.9815, expected 63.2123\n",
      "2025-05-18 21:42:51.637496: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.641174   27163 buffer_comparator.cc:157] Difference at 1068: 62.6563, expected 70.6674\n",
      "E0000 00:00:1747597371.641226   27163 buffer_comparator.cc:157] Difference at 1082: 65.0562, expected 58.3163\n",
      "E0000 00:00:1747597371.641235   27163 buffer_comparator.cc:157] Difference at 1184: 46.5451, expected 63.2182\n",
      "E0000 00:00:1747597371.641239   27163 buffer_comparator.cc:157] Difference at 1185: 46.3304, expected 60.3538\n",
      "E0000 00:00:1747597371.641243   27163 buffer_comparator.cc:157] Difference at 1186: 48.0878, expected 66.6234\n",
      "E0000 00:00:1747597371.641247   27163 buffer_comparator.cc:157] Difference at 1187: 48.7985, expected 66.5687\n",
      "E0000 00:00:1747597371.641251   27163 buffer_comparator.cc:157] Difference at 1188: 44.9372, expected 64.4337\n",
      "E0000 00:00:1747597371.641254   27163 buffer_comparator.cc:157] Difference at 1189: 51.4676, expected 71.5062\n",
      "E0000 00:00:1747597371.641258   27163 buffer_comparator.cc:157] Difference at 1190: 51.0801, expected 63.6907\n",
      "E0000 00:00:1747597371.641261   27163 buffer_comparator.cc:157] Difference at 1191: 46.534, expected 61.5592\n",
      "2025-05-18 21:42:51.641270: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.645645   27163 buffer_comparator.cc:157] Difference at 2048: 103.497, expected 67.7365\n",
      "E0000 00:00:1747597371.645722   27163 buffer_comparator.cc:157] Difference at 2049: 113.474, expected 65.8303\n",
      "E0000 00:00:1747597371.645734   27163 buffer_comparator.cc:157] Difference at 2050: 113.262, expected 72.3531\n",
      "E0000 00:00:1747597371.645738   27163 buffer_comparator.cc:157] Difference at 2051: 121.828, expected 74.5188\n",
      "E0000 00:00:1747597371.645743   27163 buffer_comparator.cc:157] Difference at 2052: 103.282, expected 63.5186\n",
      "E0000 00:00:1747597371.645746   27163 buffer_comparator.cc:157] Difference at 2053: 110.551, expected 69.9178\n",
      "E0000 00:00:1747597371.645750   27163 buffer_comparator.cc:157] Difference at 2054: 111.872, expected 69.8654\n",
      "E0000 00:00:1747597371.645753   27163 buffer_comparator.cc:157] Difference at 2055: 104.401, expected 64.2937\n",
      "E0000 00:00:1747597371.645757   27163 buffer_comparator.cc:157] Difference at 2056: 108.279, expected 69.536\n",
      "E0000 00:00:1747597371.645760   27163 buffer_comparator.cc:157] Difference at 2057: 97.8116, expected 64.4295\n",
      "2025-05-18 21:42:51.645771: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.650137   27163 buffer_comparator.cc:157] Difference at 1: 79.6034, expected 68.4472\n",
      "E0000 00:00:1747597371.650227   27163 buffer_comparator.cc:157] Difference at 3: 83.2625, expected 74.7697\n",
      "E0000 00:00:1747597371.650244   27163 buffer_comparator.cc:157] Difference at 9: 55.1642, expected 64.9645\n",
      "E0000 00:00:1747597371.650252   27163 buffer_comparator.cc:157] Difference at 11: 48.9694, expected 65.9511\n",
      "E0000 00:00:1747597371.650259   27163 buffer_comparator.cc:157] Difference at 20: 59.1144, expected 67.7619\n",
      "E0000 00:00:1747597371.650266   27163 buffer_comparator.cc:157] Difference at 30: 76.1034, expected 67.045\n",
      "E0000 00:00:1747597371.650271   27163 buffer_comparator.cc:157] Difference at 31: 49.3973, expected 61.3991\n",
      "E0000 00:00:1747597371.650277   27163 buffer_comparator.cc:157] Difference at 60: 72.8072, expected 64.4762\n",
      "E0000 00:00:1747597371.650283   27163 buffer_comparator.cc:157] Difference at 63: 72.0913, expected 64.4686\n",
      "E0000 00:00:1747597371.650288   27163 buffer_comparator.cc:157] Difference at 73: 49.6901, expected 62.2625\n",
      "2025-05-18 21:42:51.650300: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.654168   27163 buffer_comparator.cc:157] Difference at 60: 72.8072, expected 64.4762\n",
      "E0000 00:00:1747597371.654239   27163 buffer_comparator.cc:157] Difference at 63: 72.0913, expected 64.4686\n",
      "E0000 00:00:1747597371.654249   27163 buffer_comparator.cc:157] Difference at 124: 72.7795, expected 64.0992\n",
      "E0000 00:00:1747597371.654254   27163 buffer_comparator.cc:157] Difference at 188: 67.071, expected 57.3868\n",
      "E0000 00:00:1747597371.654258   27163 buffer_comparator.cc:157] Difference at 191: 65.6185, expected 58.0603\n",
      "E0000 00:00:1747597371.654262   27163 buffer_comparator.cc:157] Difference at 240: 71.0153, expected 62.5994\n",
      "E0000 00:00:1747597371.654266   27163 buffer_comparator.cc:157] Difference at 242: 69.8007, expected 61.792\n",
      "E0000 00:00:1747597371.654269   27163 buffer_comparator.cc:157] Difference at 252: 72.8146, expected 61.0918\n",
      "E0000 00:00:1747597371.654273   27163 buffer_comparator.cc:157] Difference at 316: 71.1834, expected 62.1454\n",
      "E0000 00:00:1747597371.654277   27163 buffer_comparator.cc:157] Difference at 319: 67.2516, expected 59.2762\n",
      "2025-05-18 21:42:51.654287: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.658229   27163 buffer_comparator.cc:157] Difference at 60: 72.8072, expected 64.4762\n",
      "E0000 00:00:1747597371.658351   27163 buffer_comparator.cc:157] Difference at 63: 72.0913, expected 64.4686\n",
      "E0000 00:00:1747597371.658363   27163 buffer_comparator.cc:157] Difference at 124: 72.7795, expected 64.0992\n",
      "E0000 00:00:1747597371.658369   27163 buffer_comparator.cc:157] Difference at 188: 67.071, expected 57.3868\n",
      "E0000 00:00:1747597371.658375   27163 buffer_comparator.cc:157] Difference at 191: 65.6185, expected 58.0603\n",
      "E0000 00:00:1747597371.658380   27163 buffer_comparator.cc:157] Difference at 240: 71.0153, expected 62.5994\n",
      "E0000 00:00:1747597371.658387   27163 buffer_comparator.cc:157] Difference at 242: 69.8007, expected 61.792\n",
      "E0000 00:00:1747597371.658393   27163 buffer_comparator.cc:157] Difference at 252: 72.8146, expected 61.0918\n",
      "E0000 00:00:1747597371.658399   27163 buffer_comparator.cc:157] Difference at 316: 71.1834, expected 62.1454\n",
      "E0000 00:00:1747597371.658404   27163 buffer_comparator.cc:157] Difference at 319: 67.2516, expected 59.2762\n",
      "2025-05-18 21:42:51.658420: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.662745   27163 buffer_comparator.cc:157] Difference at 4096: 72.6396, expected 63.4237\n",
      "E0000 00:00:1747597371.662817   27163 buffer_comparator.cc:157] Difference at 4097: 73.7525, expected 62.2674\n",
      "E0000 00:00:1747597371.662826   27163 buffer_comparator.cc:157] Difference at 4098: 77.184, expected 67.7224\n",
      "E0000 00:00:1747597371.662830   27163 buffer_comparator.cc:157] Difference at 4099: 81.6045, expected 68.5948\n",
      "E0000 00:00:1747597371.662834   27163 buffer_comparator.cc:157] Difference at 4100: 73.3916, expected 56.4092\n",
      "E0000 00:00:1747597371.662838   27163 buffer_comparator.cc:157] Difference at 4101: 75.407, expected 65.3777\n",
      "E0000 00:00:1747597371.662842   27163 buffer_comparator.cc:157] Difference at 4103: 73.9821, expected 58.0208\n",
      "E0000 00:00:1747597371.662846   27163 buffer_comparator.cc:157] Difference at 4104: 74.5689, expected 63.9328\n",
      "E0000 00:00:1747597371.662849   27163 buffer_comparator.cc:157] Difference at 4106: 72.4328, expected 62.842\n",
      "E0000 00:00:1747597371.662853   27163 buffer_comparator.cc:157] Difference at 4107: 69.3164, expected 59.4994\n",
      "2025-05-18 21:42:51.662864: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.667566   27163 buffer_comparator.cc:157] Difference at 4096: 72.6396, expected 63.4237\n",
      "E0000 00:00:1747597371.667661   27163 buffer_comparator.cc:157] Difference at 4097: 73.7525, expected 62.2674\n",
      "E0000 00:00:1747597371.667670   27163 buffer_comparator.cc:157] Difference at 4098: 77.184, expected 67.7224\n",
      "E0000 00:00:1747597371.667674   27163 buffer_comparator.cc:157] Difference at 4099: 81.6045, expected 68.5948\n",
      "E0000 00:00:1747597371.667678   27163 buffer_comparator.cc:157] Difference at 4100: 73.3916, expected 56.4092\n",
      "E0000 00:00:1747597371.667682   27163 buffer_comparator.cc:157] Difference at 4101: 75.407, expected 65.3777\n",
      "E0000 00:00:1747597371.667686   27163 buffer_comparator.cc:157] Difference at 4103: 73.9821, expected 58.0208\n",
      "E0000 00:00:1747597371.667689   27163 buffer_comparator.cc:157] Difference at 4104: 74.5689, expected 63.9328\n",
      "E0000 00:00:1747597371.667693   27163 buffer_comparator.cc:157] Difference at 4106: 72.4328, expected 62.842\n",
      "E0000 00:00:1747597371.667697   27163 buffer_comparator.cc:157] Difference at 4107: 69.3164, expected 59.4994\n",
      "2025-05-18 21:42:51.667707: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.671427   27163 buffer_comparator.cc:157] Difference at 4096: 72.6396, expected 63.4237\n",
      "E0000 00:00:1747597371.671483   27163 buffer_comparator.cc:157] Difference at 4097: 73.7525, expected 62.2674\n",
      "E0000 00:00:1747597371.671492   27163 buffer_comparator.cc:157] Difference at 4098: 77.184, expected 67.7224\n",
      "E0000 00:00:1747597371.671497   27163 buffer_comparator.cc:157] Difference at 4099: 81.6045, expected 68.5948\n",
      "E0000 00:00:1747597371.671501   27163 buffer_comparator.cc:157] Difference at 4100: 73.3916, expected 56.4092\n",
      "E0000 00:00:1747597371.671504   27163 buffer_comparator.cc:157] Difference at 4101: 75.407, expected 65.3777\n",
      "E0000 00:00:1747597371.671508   27163 buffer_comparator.cc:157] Difference at 4103: 73.9821, expected 58.0208\n",
      "E0000 00:00:1747597371.671511   27163 buffer_comparator.cc:157] Difference at 4104: 74.5689, expected 63.9328\n",
      "E0000 00:00:1747597371.671515   27163 buffer_comparator.cc:157] Difference at 4106: 72.4328, expected 62.842\n",
      "E0000 00:00:1747597371.671518   27163 buffer_comparator.cc:157] Difference at 4107: 69.3164, expected 59.4994\n",
      "2025-05-18 21:42:51.671527: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.675998   27163 buffer_comparator.cc:157] Difference at 8192: 34.4089, expected 65.7324\n",
      "E0000 00:00:1747597371.676055   27163 buffer_comparator.cc:157] Difference at 8193: 42.2162, expected 64.2455\n",
      "E0000 00:00:1747597371.676064   27163 buffer_comparator.cc:157] Difference at 8194: 39.1556, expected 69.0756\n",
      "E0000 00:00:1747597371.676068   27163 buffer_comparator.cc:157] Difference at 8195: 40.9391, expected 70.7496\n",
      "E0000 00:00:1747597371.676071   27163 buffer_comparator.cc:157] Difference at 8196: 33.5559, expected 60.1083\n",
      "E0000 00:00:1747597371.676075   27163 buffer_comparator.cc:157] Difference at 8197: 40.5123, expected 67.329\n",
      "E0000 00:00:1747597371.676079   27163 buffer_comparator.cc:157] Difference at 8198: 42.625, expected 68.8059\n",
      "E0000 00:00:1747597371.676082   27163 buffer_comparator.cc:157] Difference at 8199: 36.5026, expected 62.3181\n",
      "E0000 00:00:1747597371.676086   27163 buffer_comparator.cc:157] Difference at 8200: 37.0392, expected 66.8826\n",
      "E0000 00:00:1747597371.676089   27163 buffer_comparator.cc:157] Difference at 8201: 32.404, expected 62.5059\n",
      "2025-05-18 21:42:51.676099: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.679550   27163 buffer_comparator.cc:157] Difference at 8192: 34.4089, expected 65.7324\n",
      "E0000 00:00:1747597371.679604   27163 buffer_comparator.cc:157] Difference at 8193: 42.2162, expected 64.2455\n",
      "E0000 00:00:1747597371.679614   27163 buffer_comparator.cc:157] Difference at 8194: 39.1556, expected 69.0756\n",
      "E0000 00:00:1747597371.679618   27163 buffer_comparator.cc:157] Difference at 8195: 40.9391, expected 70.7496\n",
      "E0000 00:00:1747597371.679622   27163 buffer_comparator.cc:157] Difference at 8196: 33.5559, expected 60.1083\n",
      "E0000 00:00:1747597371.679626   27163 buffer_comparator.cc:157] Difference at 8197: 40.5123, expected 67.329\n",
      "E0000 00:00:1747597371.679629   27163 buffer_comparator.cc:157] Difference at 8198: 42.625, expected 68.8059\n",
      "E0000 00:00:1747597371.679633   27163 buffer_comparator.cc:157] Difference at 8199: 36.5026, expected 62.3181\n",
      "E0000 00:00:1747597371.679636   27163 buffer_comparator.cc:157] Difference at 8200: 37.0392, expected 66.8826\n",
      "E0000 00:00:1747597371.679640   27163 buffer_comparator.cc:157] Difference at 8201: 32.404, expected 62.5059\n",
      "2025-05-18 21:42:51.679649: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.683382   27163 buffer_comparator.cc:157] Difference at 0: 62.5199, expected 69.6635\n",
      "E0000 00:00:1747597371.683519   27163 buffer_comparator.cc:157] Difference at 10: 55.3989, expected 65.043\n",
      "E0000 00:00:1747597371.683544   27163 buffer_comparator.cc:157] Difference at 11: 57.2411, expected 65.9511\n",
      "E0000 00:00:1747597371.683554   27163 buffer_comparator.cc:157] Difference at 31: 52.9188, expected 61.3991\n",
      "E0000 00:00:1747597371.683563   27163 buffer_comparator.cc:157] Difference at 36: 59.1212, expected 66.5532\n",
      "E0000 00:00:1747597371.683571   27163 buffer_comparator.cc:157] Difference at 45: 59.9638, expected 67.3664\n",
      "E0000 00:00:1747597371.683580   27163 buffer_comparator.cc:157] Difference at 64: 59.6322, expected 66.9789\n",
      "E0000 00:00:1747597371.683588   27163 buffer_comparator.cc:157] Difference at 68: 54.2269, expected 62.385\n",
      "E0000 00:00:1747597371.683595   27163 buffer_comparator.cc:157] Difference at 74: 49.5086, expected 64.7137\n",
      "E0000 00:00:1747597371.683603   27163 buffer_comparator.cc:157] Difference at 75: 51.86, expected 61.9036\n",
      "2025-05-18 21:42:51.683619: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "E0000 00:00:1747597371.687762   27163 buffer_comparator.cc:157] Difference at 8192: 32.6718, expected 65.7324\n",
      "E0000 00:00:1747597371.687818   27163 buffer_comparator.cc:157] Difference at 8193: 40.8719, expected 64.2455\n",
      "E0000 00:00:1747597371.687827   27163 buffer_comparator.cc:157] Difference at 8194: 37.1973, expected 69.0756\n",
      "E0000 00:00:1747597371.687831   27163 buffer_comparator.cc:157] Difference at 8195: 38.6364, expected 70.7496\n",
      "E0000 00:00:1747597371.687835   27163 buffer_comparator.cc:157] Difference at 8196: 31.5812, expected 60.1083\n",
      "E0000 00:00:1747597371.687839   27163 buffer_comparator.cc:157] Difference at 8197: 37.2323, expected 67.329\n",
      "E0000 00:00:1747597371.687842   27163 buffer_comparator.cc:157] Difference at 8198: 40.3521, expected 68.8059\n",
      "E0000 00:00:1747597371.687846   27163 buffer_comparator.cc:157] Difference at 8199: 33.7122, expected 62.3181\n",
      "E0000 00:00:1747597371.687850   27163 buffer_comparator.cc:157] Difference at 8200: 34.9375, expected 66.8826\n",
      "E0000 00:00:1747597371.687853   27163 buffer_comparator.cc:157] Difference at 8201: 31.7167, expected 62.5059\n",
      "2025-05-18 21:42:51.687862: E external/local_xla/xla/service/gpu/autotuning/gemm_fusion_autotuner.cc:987] Results do not match the reference. This is likely a bug/unexpected loss of precision.\n",
      "W0000 00:00:1747597371.925965   27163 gpu_backend_lib.cc:617] libdevice is required by this HLO module but was not found at ./libdevice.10.bc\n",
      "2025-05-18 21:42:51.929668: W tensorflow/core/framework/op_kernel.cc:1841] OP_REQUIRES failed at xla_ops.cc:577 : INTERNAL: libdevice not found at ./libdevice.10.bc\n",
      "2025-05-18 21:42:51.929779: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INTERNAL: libdevice not found at ./libdevice.10.bc\n",
      "\t [[{{node StatefulPartitionedCall}}]]\n"
     ]
    },
    {
     "ename": "InternalError",
     "evalue": "Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 645, in run_forever\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 1999, in _run_once\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3153, in _run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3365, in run_cell_async\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3610, in run_ast_nodes\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3670, in run_code\n\n  File \"/tmp/ipykernel_879/1271964287.py\", line 10, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nlibdevice not found at ./libdevice.10.bc\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_1828]",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mInternalError\u001b[39m                             Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[6]\u001b[39m\u001b[32m, line 10\u001b[39m\n\u001b[32m      1\u001b[39m model = keras.Sequential([\n\u001b[32m      2\u001b[39m     layers.Dense(\u001b[32m128\u001b[39m, activation=\u001b[33m'\u001b[39m\u001b[33mrelu\u001b[39m\u001b[33m'\u001b[39m, input_shape=input_shape),\n\u001b[32m      3\u001b[39m     layers.Dense(\u001b[32m64\u001b[39m, activation=\u001b[33m'\u001b[39m\u001b[33mrelu\u001b[39m\u001b[33m'\u001b[39m),\n\u001b[32m      4\u001b[39m     layers.Dense(\u001b[32m1\u001b[39m)\n\u001b[32m      5\u001b[39m ])\n\u001b[32m      6\u001b[39m model.compile(\n\u001b[32m      7\u001b[39m     optimizer=\u001b[33m'\u001b[39m\u001b[33madam\u001b[39m\u001b[33m'\u001b[39m,\n\u001b[32m      8\u001b[39m     loss=\u001b[33m'\u001b[39m\u001b[33mmae\u001b[39m\u001b[33m'\u001b[39m,\n\u001b[32m      9\u001b[39m )\n\u001b[32m---> \u001b[39m\u001b[32m10\u001b[39m history = \u001b[43mmodel\u001b[49m\u001b[43m.\u001b[49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[32m     11\u001b[39m \u001b[43m    \u001b[49m\u001b[43mX_train\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_train\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     12\u001b[39m \u001b[43m    \u001b[49m\u001b[43mvalidation_data\u001b[49m\u001b[43m=\u001b[49m\u001b[43m(\u001b[49m\u001b[43mX_valid\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43my_valid\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[32m     13\u001b[39m \u001b[43m    \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m512\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m     14\u001b[39m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[43m=\u001b[49m\u001b[32;43m50\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[32m     15\u001b[39m \u001b[43m)\u001b[49m\n\u001b[32m     16\u001b[39m history_df = pd.DataFrame(history.history)\n\u001b[32m     17\u001b[39m history_df.loc[:, [\u001b[33m'\u001b[39m\u001b[33mloss\u001b[39m\u001b[33m'\u001b[39m, \u001b[33m'\u001b[39m\u001b[33mval_loss\u001b[39m\u001b[33m'\u001b[39m]].plot()\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py:122\u001b[39m, in \u001b[36mfilter_traceback.<locals>.error_handler\u001b[39m\u001b[34m(*args, **kwargs)\u001b[39m\n\u001b[32m    119\u001b[39m     filtered_tb = _process_traceback_frames(e.__traceback__)\n\u001b[32m    120\u001b[39m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[32m    121\u001b[39m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[32m--> \u001b[39m\u001b[32m122\u001b[39m     \u001b[38;5;28;01mraise\u001b[39;00m e.with_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m\u001b[38;5;250m \u001b[39m\u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[32m    123\u001b[39m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[32m    124\u001b[39m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "\u001b[36mFile \u001b[39m\u001b[32m~/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tensorflow/python/eager/execute.py:53\u001b[39m, in \u001b[36mquick_execute\u001b[39m\u001b[34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[39m\n\u001b[32m     51\u001b[39m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[32m     52\u001b[39m   ctx.ensure_initialized()\n\u001b[32m---> \u001b[39m\u001b[32m53\u001b[39m   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[32m     54\u001b[39m                                       inputs, attrs, num_outputs)\n\u001b[32m     55\u001b[39m \u001b[38;5;28;01mexcept\u001b[39;00m core._NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[32m     56\u001b[39m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[31mInternalError\u001b[39m: Graph execution error:\n\nDetected at node StatefulPartitionedCall defined at (most recent call last):\n  File \"<frozen runpy>\", line 198, in _run_module_as_main\n\n  File \"<frozen runpy>\", line 88, in _run_code\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 645, in run_forever\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/base_events.py\", line 1999, in _run_once\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/asyncio/events.py\", line 88, in _run\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3098, in run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3153, in _run_cell\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3365, in run_cell_async\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3610, in run_ast_nodes\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/IPython/core/interactiveshell.py\", line 3670, in run_code\n\n  File \"/tmp/ipykernel_879/1271964287.py\", line 10, in <module>\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 371, in fit\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 219, in function\n\n  File \"/home/caujoulat/miniforge3/envs/EnvDL/lib/python3.12/site-packages/keras/src/backend/tensorflow/trainer.py\", line 132, in multi_step_on_iterator\n\nlibdevice not found at ./libdevice.10.bc\n\t [[{{node StatefulPartitionedCall}}]] [Op:__inference_multi_step_on_iterator_1828]"
     ]
    }
   ],
   "source": [
    "model = keras.Sequential([\n",
    "    layers.Dense(128, activation='relu', input_shape=input_shape),\n",
    "    layers.Dense(64, activation='relu'),\n",
    "    layers.Dense(1)\n",
    "])\n",
    "model.compile(\n",
    "    optimizer='adam',\n",
    "    loss='mae',\n",
    ")\n",
    "history = model.fit(\n",
    "    X_train, y_train,\n",
    "    validation_data=(X_valid, y_valid),\n",
    "    batch_size=512,\n",
    "    epochs=50,\n",
    ")\n",
    "history_df = pd.DataFrame(history.history)\n",
    "history_df.loc[:, ['loss', 'val_loss']].plot()\n",
    "print(\"Minimum Validation Loss: {:0.4f}\".format(history_df['val_loss'].min()));"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4e7fa700-990e-431c-a713-375eeec30b72",
   "metadata": {},
   "source": [
    "## 2) Add capacity"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "d46d168c-dc3d-4a5e-9f69-983792757904",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/javascript": [
       "parent.postMessage({\"jupyterEvent\": \"custom.exercise_interaction\", \"data\": {\"outcomeType\": 1, \"valueTowardsCompletion\": 0.25, \"interactionType\": 1, \"questionType\": 4, \"questionId\": \"2_Q2\", \"learnToolsVersion\": \"0.3.5\", \"failureMessage\": \"\", \"exceptionClass\": \"\", \"trace\": \"\"}}, \"*\")"
      ],
      "text/plain": [
       "<IPython.core.display.Javascript object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/markdown": [
       "<span style=\"color:#33cc33\">Correct:</span> \n",
       "\n",
       "Now the validation loss begins to rise very early, while the training loss continues to decrease. This indicates that the network has begun to overfit. At this point, we would need to try something to prevent it, either by reducing the number of units or through a method like early stopping. (We'll see another in the next lesson!)"
      ],
      "text/plain": [
       "Correct: \n",
       "\n",
       "Now the validation loss begins to rise very early, while the training loss continues to decrease. This indicates that the network has begun to overfit. At this point, we would need to try something to prevent it, either by reducing the number of units or through a method like early stopping. (We'll see another in the next lesson!)"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "# View the solution (Run this cell to receive credit!)\n",
    "q_2.check()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "06d5be1d-c8e8-45a9-89b9-045a193beb23",
   "metadata": {},
   "source": [
    "## 3) Define Early Stopping Callback"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "f5f82519-2216-41a2-8818-0509232d08ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "application/javascript": [
       "parent.postMessage({\"jupyterEvent\": \"custom.exercise_interaction\", \"data\": {\"outcomeType\": 2, \"failureMessage\": \"The `min_delta` argument should be 0.001.\", \"interactionType\": 1, \"questionType\": 2, \"questionId\": \"3_Q3\", \"learnToolsVersion\": \"0.3.5\", \"valueTowardsCompletion\": 0.0, \"exceptionClass\": \"\", \"trace\": \"\"}}, \"*\")"
      ],
      "text/plain": [
       "<IPython.core.display.Javascript object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/markdown": [
       "<span style=\"color:#cc3333\">Incorrect:</span> The `min_delta` argument should be 0.001."
      ],
      "text/plain": [
       "Incorrect: The `min_delta` argument should be 0.001."
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "from tensorflow.keras import callbacks\n",
    "from tensorflow.keras.callbacks import EarlyStopping\n",
    "\n",
    "# YOUR CODE HERE: define an early stopping callback\n",
    "early_stopping = EarlyStopping(\n",
    "    min_delta=0.001, # minimium amount of change to count as an improvement\n",
    "    patience=5, # how many epochs to wait before stopping\n",
    "    restore_best_weights=True,\n",
    ")\n",
    "\n",
    "# Check your answer\n",
    "q_3.check()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "381db53f-30e9-43c8-957b-11ebeec2eb6f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.10"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
